# Site settings
title: 5srd
baseurl: ""
url: "http://5srd.com"

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - tables
    - with_toc_data
    - footnotes
    - smart

exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - vendor/bootstrap/docs

keep_files:
  - vendor

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: ogl-notice
  - scope:
      path: ""
      type: classes
    values:
      layout: class
  - scope:
      path: ""
      type: languages
    values:
      layout: language
  - scope:
      path: ""
      type: poisons
    values:
      layout: poison
  - scope:
      path: ""
      type: spells
    values:
      layout: spell

collections:
  animals:
    permalink: /:collection/:title/
    output: true
  backgrounds:
    permalink: /:collection/:title/
    output: true
  feats:
    permalink: /:collection/:title/
    output: true
  classes:
    permalink: /:collection/:title/
    output: true
  diseases:
    permalink: /:collection/:title/
    output: true
  languages:
    permalink: /:collection/:title/
    output: true
  magic-items:
    permalink: /:collection/:title/
    output: true
  monsters:
    permalink: /:collection/:title/
    output: true
  npcs:
    permalink: /:collection/:title/
    output: true
  poisons:
    permalink: /:collection/:title/
    output: true
  races:
    permalink: /:collection/:title/
    output: true
  spells:
    permalink: /:collection/:title/
    output: true
  traps:
    permalink: /:collection/:title/
    output: true

array: []
