# Site settings
title: 5srd
baseurl: ""
url: "http://5srd.com"

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - tables
    - with_toc_data
    - footnotes
    - smart

exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - vendor/bootstrap/docs

keep_files:
  - vendor

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: ogl-notice
  - scope:
      path: ""
      type: classes
    values:
      layout: class
  - scope:
      path: ""
      type: languages
    values:
      layout: language
  - scope:
      path: ""
      type: monsters
    values:
      layout: monster
  - scope:
      path: ""
      type: poisons
    values:
      layout: poison
  - scope:
      path: ""
      type: spells
    values:
      layout: spell

collections:
  animals:
    permalink: /:collection/:title/
    output: true
  backgrounds:
    permalink: /:collection/:title/
    output: true
  feats:
    permalink: /:collection/:title/
    output: true
  classes:
    permalink: /:collection/:title/
    output: true
  diseases:
    permalink: /:collection/:title/
    output: true
  languages:
    permalink: /:collection/:title/
    output: true
  magic-items:
    permalink: /:collection/:title/
    output: true
  monsters:
    permalink: /:collection/:title/
    output: true
  npcs:
    permalink: /:collection/:title/
    output: true
  poisons:
    permalink: /:collection/:title/
    output: true
  races:
    permalink: /:collection/:title/
    output: true
  spells:
    permalink: /:collection/:title/
    output: true
  traps:
    permalink: /:collection/:title/
    output: true

array: []

challenge_xp:
  - rating: 0
    xp: 0
  - rating: 0.125
    xp: 25
  - rating: 0.25
    xp: 50
  - rating: 0.5
    xp: 100
  - rating: 1
    xp: 200
  - rating: 2
    xp: 450
  - rating: 3
    xp: 700
  - rating: 4
    xp: 1100
  - rating: 5
    xp: 1800
  - rating: 6
    xp: 2300
  - rating: 7
    xp: 2900
  - rating: 8
    xp: 3900
  - rating: 9
    xp: 5000
  - rating: 10
    xp: 5900
  - rating: 11
    xp: 7200
  - rating: 12
    xp: 8400
  - rating: 13
    xp: 10000
  - rating: 14
    xp: 11500
  - rating: 15
    xp: 13000
  - rating: 16
    xp: 15000
  - rating: 17
    xp: 18000
  - rating: 18
    xp: 20000
  - rating: 19
    xp: 22000
  - rating: 20
    xp: 25000
  - rating: 21
    xp: 33000
  - rating: 22
    xp: 41000
  - rating: 23
    xp: 50000
  - rating: 24
    xp: 62000
  - rating: 25
    xp: 75000
  - rating: 26
    xp: 90000
  - rating: 27
    xp: 105000
  - rating: 28
    xp: 120000
  - rating: 29
    xp: 135000
  - rating: 30
    xp: 155000
