# Site settings
title: 5srd
baseurl: ""
url: "http://5srd.com"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data", "footnotes"]

exclude:
  - CNAME
  - README.md
  - vendor/bootstrap/docs

keep_files:
  - vendor

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: ogl-notice
  - scope:
      path: ""
      type: spells
    values:
      layout: spell
  - scope:
      path: ""
      type: languages
    values:
      layout: language

collections:
  animals:
    title: "Animals"
    permalink: /:collection/:title/
    output: true
  backgrounds:
    title: "Backgrounds"
    permalink: /:collection/:title/
    output: true
  classes:
    title: "Classes"
    permalink: /:collection/:title/
    output: true
  languages:
    title: "Languages"
    permalink: /:collection/:title/
    output: true
  magic-items:
    title: "Magic Items"
    permalink: /:collection/:title/
    output: true
  monsters:
    title: "Monsters"
    permalink: /:collection/:title/
    output: true
  npcs:
    title: "NPCs"
    permalink: /:collection/:title/
    output: true
  races:
    title: "Races"
    permalink: /:collection/:title/
    output: true
  spells:
    title: "Spells"
    permalink: /:collection/:title/
    output: true
